[build]
  command = "pnpm install --include=dev && pnpm --dir frontend install --include=dev && pnpm run build"
  publish = "frontend/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
